language: python

services:
  - docker

python:
  - "3.5"

# command to install dependencies
before_install:
- docker build --force-rm=true --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE} --build-arg TRAVIS_PULL_REQUEST_SLUG=${TRAVIS_PULL_REQUEST_SLUG} --build-arg TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH} -t odie-ubuntu1604 -f docker/ubuntu_16_04.dockerfile .
- docker build --force-rm=true --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE} --build-arg TRAVIS_PULL_REQUEST_SLUG=${TRAVIS_PULL_REQUEST_SLUG} --build-arg TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH} -t odie-debian8 -f docker/debian8.dockerfile .
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
- sudo apt-get update
- sudo apt-get install $(cat install/files/deb-packages_requirements.txt)
- sudo apt-get install libstdc++6
- wget https://bootstrap.pypa.io/get-pip.py
- sudo python get-pip.py

install:
  - pip install -r install/files/python_requirements.txt
  - pip install python2-pythondialog || pip install pythondialog
  - pip install coveralls

# command to run tests
script:
#  - pytest
  - docker run -it --rm odie-ubuntu1604
  - docker run -it --rm odie-debian9
  - coverage run --source=Tests -m unittest discover

after_success:
  coveralls

